### ISSUE TITLE
Create an Icon component

### ISSUE THREAD

**Issue by geraldiner** [geraldiner/advent-of-js-and-css-2023#3]
Based on Advent of CSS [Challenge #1](https://store.selfteach.me/view/courses/advent-of-css-2022/2307198-challenge-1-building-an-icon-component/7338197-challenge-1)

Create an `Icon` component that:

* Accepts a `name` prop that is required.
* Accepts a `size` prop that is optional. The default value should be `24`.
* Returns an `<svg>` with the given `name` and `size`. Returns `null` if no `name` is given.

Approach:

- [x] Create an `Icon.jsx` file in the `client/src/components` folder.
- [x] Give it some basic pieces so you know it will render something when used (see [Footer.jsx](https://github.com/geraldiner/advent-of-js-and-css-2023/blob/staging/client/src/components/Footer.jsx) as an example).
- [x] Get `Icon.jsx` rendered on [LoginPage.jsx](https://github.com/geraldiner/advent-of-js-and-css-2023/blob/staging/client/src/routes/LoginPage.jsx).
  * Notice how `Footer.jsx` is being rendered in this file.
- [x] Now try to get `Icon.jsx` to render an `svg` image instead (try hardcoding one of the actual icon images from `client/src/images/icons`).
- [x] Now try to get `Icon.jsx` to accept a `prop` that allows it to render a specific icon image based on an `id`.
- [x] Now try to get `Icon.jsx` to accept a `prop` that allows it to render at a specific size.
- [x] Now update the `Icon` component on `LoginPage.jsx` and pass a `id` prop, ex: `<Icon id="calendar" />`.
- [x] Review the requirements above (3 bullets above this list) and ensure that the `Icon` component behaves as it's supposed to.

**Comment by dominionworkz** [comment]
The addition I believe that this will help, Thanks!!
